### ISSUE TITLE
[Back] Implementação de alteração de situação de escolas

### ISSUE THREAD

**Issue by CarolinaBarb** [fga-eps-mds/2023.1-Dnit-EscolaService#1]
## Implementação
Deve-se realizar a implementação da edição da situação de escolas, realizando a comunicação com banco de dado de dev

## D.O.D
- [x] Print do swagger com endpoint
- [x] Print do banco de dados com a situações de escolas

**Comment by GuilhermeSoaress** [comment]
![Image](https://github.com/fga-eps-mds/2023.1-DNIT-EscolaService/assets/88786065/a05eb38f-86ab-4f03-a93e-e3ec3493951f)




![Image](https://github.com/fga-eps-mds/2023.1-DNIT-EscolaService/assets/88786065/fc8361d9-e268-4dfd-a0f3-7812cdbe7eb8)




![Image](https://github.com/fga-eps-mds/2023.1-DNIT-EscolaService/assets/88786065/2d2628ef-92c9-4491-a3ec-5d68cfee7337)
