### ISSUE TITLE
[Back] Implementação da importação de planilhas

### ISSUE THREAD

**Issue by Fealps** [fga-eps-mds/2023.1-Dnit-EscolaService#21]
## Implementação
Deve-se realizar a implementação do endpoint para cadastro de escolas através de planilhas, realizando a comunicação com banco de dado de dev

## D.O.D
- [ ] Print do swagger com endpoint
- [ ] Print do banco de dados com a view de uma escola cadastrada
- [x] Testes

**Comment by antoniotoineto** [comment]
## Swagger:


![Image](https://github.com/fga-eps-mds/2023.1-Dnit-EscolaService/assets/54555684/9d534f4a-5fd4-4b1f-bf3a-9f8ee5c9ef8a)


## Banco de dados:



![Image](https://github.com/fga-eps-mds/2023.1-Dnit-EscolaService/assets/54555684/2bbf2cec-30cd-4af9-9c3f-644e7ea8bdb1)

## Planilha



![Image](https://github.com/fga-eps-mds/2023.1-Dnit-EscolaService/assets/54555684/270e19ec-6d69-4860-877f-49e63e66d9bc)
