### ISSUE TITLE
[Back] Funcionalidades referentes a filtragem da escola

### ISSUE THREAD

**Issue by antoniotoineto** [fga-eps-mds/2023.1-Dnit-EscolaService#34]
## D.O.D

- [x] Não diferenciar maiúscula e minúsculo ao filtrar escolas
- [x] Etapas de ensino permitir mais de um valor

## Imagens:
Não diferenciar maiúscula e minúsculo ao filtrar escolas
![image](https://github.com/fga-eps-mds/2023.1-Dnit-EscolaService/assets/89492943/d609c455-a5b4-4262-b175-bd8d2b979c0b)
Não diferenciar maiúscula e minúsculo ao filtrar escolas
![image](https://github.com/fga-eps-mds/2023.1-Dnit-EscolaService/assets/89492943/01772baa-66b7-4c5b-b0f9-bc8e4cf27eca)
![image](https://github.com/fga-eps-mds/2023.1-Dnit-EscolaService/assets/89492943/69c8bbff-c856-4d3a-9cec-da89683c1209)

**Comment by DenysRogeres** [comment]
Finalizado
