### ISSUE TITLE
[Back] Hotfix na exibicao de informacao de escola

### ISSUE THREAD

**Issue by GuilhermeSoaress** [fga-eps-mds/2023.1-Dnit-EscolaService#35]
### D.O.D

- [x] Permitir alguns campos editáveis (telefone, lat, long, nº de alunos, nº de docentes e observações)
- [x] Print do campo de última atualização do banco
- [x] Print do Swagger com endpoints para UPTADE na tabela
- [x] Adicionar o campo de última atualização

**Comment by CarolinaBarb** [comment]
![Image](https://github.com/fga-eps-mds/2023.1-Dnit-EscolaService/assets/98655636/433f94c9-4ada-44d1-b13b-b4ccc52ada2c)
