### ISSUE TITLE
[Back] Implementação de remoção de situação de escolas

### ISSUE THREAD

**Issue by Fealps** [fga-eps-mds/2023.1-Dnit-EscolaService#4]
## Implementação
Deve-se realizar a implementação da remoção de uma situação de escolas, realizando a comunicação com banco de dado de dev

## D.O.D
- [x] Print do swagger com endpoint
- [x] Print do banco de dados com a situações de escolas
-  - [x] Antes de removido
-  - [x] Depois de removido

**Comment by GuilhermeSoaress** [comment]
## Imagens:
### Endpoint para remover situação de uma escola:
![image](https://github.com/fga-eps-mds/2023.1-DNIT-EscolaService/assets/88786065/be51b94d-b153-4d77-aa49-ad69f58a114b)
### Print do banco de dados antes da situação da escola ser removida:
![image](https://github.com/fga-eps-mds/2023.1-DNIT-EscolaService/assets/88786065/c7078907-27d2-4f47-890a-905867caf242)
### Print do banco de dados depois da situação da escola ser removida:
![image](https://github.com/fga-eps-mds/2023.1-DNIT-EscolaService/assets/88786065/85a03904-217b-4964-aa31-72beeebb72ee)
