### ISSUE TITLE
[Back] implementação para visualização de escolas

### ISSUE THREAD

**Issue by Fealps** [fga-eps-mds/2023.1-Dnit-EscolaService#5]
## Implementação
Deve-se realizar a implementação da view para visualização de escolas, realizando a comunicação com banco de dado de dev

## D.O.D
- [x] Print do swagger com endpoint
- [x] Print do banco de dados com a view de uma escola cadastrada

**Comment by JuliaSSouza** [comment]
![Image](https://github.com/fga-eps-mds/2023.1-DNIT-EscolaService/assets/88839152/b9b7c784-0c5b-4c16-b6c3-096347512cd9)



![Image](https://github.com/fga-eps-mds/2023.1-DNIT-EscolaService/assets/88839152/ce00dd72-e37b-418a-a297-84956803aff8)
