### ISSUE TITLE
[Back] Implementação de exclusão de escolas

### ISSUE THREAD

**Issue by Fealps** [fga-eps-mds/2023.1-Dnit-EscolaService#8]
## Implementação
Deve-se realizar a implementação da exclusão de escolas, realizando a comunicação com banco de dado de dev

## D.O.D
- [x] Print do swagger com endpoint
- [x] Print do banco de dados com:
- - [x] Antes da escola ser excluída
- - [x] Depois da escola ser excluída

**Comment by yan-luca** [comment]
![Captura de tela 2023-06-10 151823](https://github.com/fga-eps-mds/2023.1-DNIT-EscolaService/assets/108501120/2d8ff95e-a95c-4f75-a2e3-9684e49fd4e9)

![swagger](https://github.com/fga-eps-mds/2023.1-DNIT-EscolaService/assets/108501120/c6e8c930-e764-4c96-8e26-d1cefbf05694)

![escolacastrada](https://github.com/fga-eps-mds/2023.1-DNIT-EscolaService/assets/108501120/305f9415-c5a5-42dc-b360-43feecda4309)

![escolaexcluida](https://github.com/fga-eps-mds/2023.1-DNIT-EscolaService/assets/108501120/41b58b92-f57c-47d8-852b-9cd2bfe68b54)
